services:
  hardcover-import-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: hardcover-import-service:latest
    hostname: hardcover-import-service.mediamaster.internal
    container_name: hardcover-import-service.mediamaster.internal
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mediamaster-internal-network

networks:
  mediamaster-internal-network:
    name: mediamaster-internal-network
